#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v25
# autospec commit: 9594167
#
# Source0 file verified with key 0xF63412E60947D6EF (marius.vlad@collabora.com)
#
Name     : weston
Version  : 14.0.2
Release  : 31
URL      : https://gitlab.freedesktop.org/wayland/weston/-/releases/14.0.2/downloads/weston-14.0.2.tar.xz
Source0  : https://gitlab.freedesktop.org/wayland/weston/-/releases/14.0.2/downloads/weston-14.0.2.tar.xz
Source1  : https://gitlab.freedesktop.org/wayland/weston/-/releases/14.0.2/downloads/weston-14.0.2.tar.xz.sig
Source2  : F63412E60947D6EF.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : CC-BY-SA-3.0 MIT
Requires: weston-bin = %{version}-%{release}
Requires: weston-data = %{version}-%{release}
Requires: weston-lib = %{version}-%{release}
Requires: weston-libexec = %{version}-%{release}
Requires: weston-license = %{version}-%{release}
Requires: weston-man = %{version}-%{release}
BuildRequires : FreeRDP-dev
BuildRequires : FreeRDP2-dev
BuildRequires : Linux-PAM-dev
BuildRequires : buildreq-meson
BuildRequires : cairo-dev
BuildRequires : doxygen
BuildRequires : gnupg
BuildRequires : gstreamer-dev
BuildRequires : lcms2-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libva-dev
BuildRequires : libwebp-dev
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(egl)
BuildRequires : pkgconfig(gbm)
BuildRequires : pkgconfig(gstreamer-1.0)
BuildRequires : pkgconfig(gstreamer-allocators-1.0)
BuildRequires : pkgconfig(libdisplay-info)
BuildRequires : pkgconfig(libdrm)
BuildRequires : pkgconfig(libevdev)
BuildRequires : pkgconfig(libinput)
BuildRequires : pkgconfig(libpipewire-0.3)
BuildRequires : pkgconfig(libseat)
BuildRequires : pkgconfig(libva)
BuildRequires : pkgconfig(libwebp)
BuildRequires : pkgconfig(mtdev)
BuildRequires : pkgconfig(pango)
BuildRequires : pkgconfig(pangocairo)
BuildRequires : pkgconfig(pixman-1)
BuildRequires : pkgconfig(wayland-protocols)
BuildRequires : pkgconfig(xcb-cursor)
BuildRequires : pkgconfig(xcursor)
BuildRequires : pkgconfig(xkbcommon)
BuildRequires : pkgconfig(xwayland)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
WCAP Tools
WCAP is the video capture format used by Weston (Weston CAPture).
It's a simple, lossless format, that encodes the difference between
frames as run-length encoded rectangles.  It's a variable framerate
format, that only records new frames along with a timestamp when
something actually changes.

%package bin
Summary: bin components for the weston package.
Group: Binaries
Requires: weston-data = %{version}-%{release}
Requires: weston-libexec = %{version}-%{release}
Requires: weston-license = %{version}-%{release}

%description bin
bin components for the weston package.


%package data
Summary: data components for the weston package.
Group: Data

%description data
data components for the weston package.


%package dev
Summary: dev components for the weston package.
Group: Development
Requires: weston-lib = %{version}-%{release}
Requires: weston-bin = %{version}-%{release}
Requires: weston-data = %{version}-%{release}
Provides: weston-devel = %{version}-%{release}
Requires: weston = %{version}-%{release}

%description dev
dev components for the weston package.


%package extras
Summary: extras components for the weston package.
Group: Default

%description extras
extras components for the weston package.


%package lib
Summary: lib components for the weston package.
Group: Libraries
Requires: weston-data = %{version}-%{release}
Requires: weston-libexec = %{version}-%{release}
Requires: weston-license = %{version}-%{release}

%description lib
lib components for the weston package.


%package libexec
Summary: libexec components for the weston package.
Group: Default
Requires: weston-license = %{version}-%{release}

%description libexec
libexec components for the weston package.


%package license
Summary: license components for the weston package.
Group: Default

%description license
license components for the weston package.


%package man
Summary: man components for the weston package.
Group: Default

%description man
man components for the weston package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) F63412E60947D6EF' gpg.status
%setup -q -n weston-14.0.2
cd %{_builddir}/weston-14.0.2
pushd ..
cp -a weston-14.0.2 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1746136606
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dbackend-vnc=false  builddir
ninja -v -C builddir
GOAMD64=v3
CFLAGS="$CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dbackend-vnc=false  builddiravx2
ninja -v -C builddiravx2

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/weston
cp %{_builddir}/weston-%{version}/COPYING %{buildroot}/usr/share/package-licenses/weston/3cdd630da43ea78f8ca83b291afcce3fa388a804 || :
cp %{_builddir}/weston-%{version}/data/COPYING %{buildroot}/usr/share/package-licenses/weston/5648ca4646a6d77ee875a10a0f8a576f59d8cb44 || :
GOAMD64=v3
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
## Remove excluded files
rm -f %{buildroot}*/usr/bin/weston-screenshooter
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/wcap-decode
/V3/usr/bin/weston
/V3/usr/bin/weston-constraints
/V3/usr/bin/weston-content_protection
/V3/usr/bin/weston-debug
/V3/usr/bin/weston-simple-dmabuf-egl
/V3/usr/bin/weston-simple-dmabuf-feedback
/V3/usr/bin/weston-tablet
/V3/usr/bin/weston-terminal
/V3/usr/bin/weston-touch-calibrator
/usr/bin/wcap-decode
/usr/bin/weston
/usr/bin/weston-constraints
/usr/bin/weston-content_protection
/usr/bin/weston-debug
/usr/bin/weston-simple-dmabuf-egl
/usr/bin/weston-simple-dmabuf-feedback
/usr/bin/weston-tablet
/usr/bin/weston-terminal
/usr/bin/weston-touch-calibrator

%files data
%defattr(-,root,root,-)
/usr/share/libweston-14/protocols/weston-content-protection.xml
/usr/share/libweston-14/protocols/weston-debug.xml
/usr/share/libweston-14/protocols/weston-direct-display.xml
/usr/share/libweston-14/protocols/weston-output-capture.xml
/usr/share/wayland-sessions/weston.desktop
/usr/share/weston/background.png
/usr/share/weston/border.png
/usr/share/weston/fullscreen.png
/usr/share/weston/home.png
/usr/share/weston/icon_editor.png
/usr/share/weston/icon_flower.png
/usr/share/weston/icon_ivi_clickdot.png
/usr/share/weston/icon_ivi_flower.png
/usr/share/weston/icon_ivi_simple-egl.png
/usr/share/weston/icon_ivi_simple-shm.png
/usr/share/weston/icon_ivi_smoke.png
/usr/share/weston/icon_terminal.png
/usr/share/weston/icon_window.png
/usr/share/weston/panel.png
/usr/share/weston/pattern.png
/usr/share/weston/random.png
/usr/share/weston/sidebyside.png
/usr/share/weston/sign_close.png
/usr/share/weston/sign_maximize.png
/usr/share/weston/sign_minimize.png
/usr/share/weston/terminal.png
/usr/share/weston/tiling.png
/usr/share/weston/wayland.png
/usr/share/weston/wayland.svg

%files dev
%defattr(-,root,root,-)
/usr/include/libweston-14/libweston/backend-drm.h
/usr/include/libweston-14/libweston/backend-headless.h
/usr/include/libweston-14/libweston/backend-pipewire.h
/usr/include/libweston-14/libweston/backend-rdp.h
/usr/include/libweston-14/libweston/backend-wayland.h
/usr/include/libweston-14/libweston/backend-x11.h
/usr/include/libweston-14/libweston/config-parser.h
/usr/include/libweston-14/libweston/desktop.h
/usr/include/libweston-14/libweston/libweston.h
/usr/include/libweston-14/libweston/matrix.h
/usr/include/libweston-14/libweston/pipewire-plugin.h
/usr/include/libweston-14/libweston/plugin-registry.h
/usr/include/libweston-14/libweston/remoting-plugin.h
/usr/include/libweston-14/libweston/shell-utils.h
/usr/include/libweston-14/libweston/version.h
/usr/include/libweston-14/libweston/weston-log.h
/usr/include/libweston-14/libweston/windowed-output-api.h
/usr/include/libweston-14/libweston/xwayland-api.h
/usr/include/libweston-14/libweston/zalloc.h
/usr/include/weston/ivi-layout-export.h
/usr/include/weston/weston.h
/usr/lib64/libweston-14.so
/usr/lib64/pkgconfig/libweston-14.pc
/usr/lib64/pkgconfig/weston.pc
/usr/share/pkgconfig/libweston-14-protocols.pc

%files extras
%defattr(-,root,root,-)
/V3/usr/bin/weston-calibrator
/V3/usr/bin/weston-clickdot
/V3/usr/bin/weston-cliptest
/V3/usr/bin/weston-dnd
/V3/usr/bin/weston-editor
/V3/usr/bin/weston-eventdemo
/V3/usr/bin/weston-flower
/V3/usr/bin/weston-fullscreen
/V3/usr/bin/weston-image
/V3/usr/bin/weston-multi-resource
/V3/usr/bin/weston-presentation-shm
/V3/usr/bin/weston-resizor
/V3/usr/bin/weston-scaler
/V3/usr/bin/weston-simple-damage
/V3/usr/bin/weston-simple-dmabuf-v4l
/V3/usr/bin/weston-simple-egl
/V3/usr/bin/weston-simple-shm
/V3/usr/bin/weston-simple-touch
/V3/usr/bin/weston-smoke
/V3/usr/bin/weston-stacking
/V3/usr/bin/weston-subsurfaces
/V3/usr/bin/weston-transformed
/usr/bin/weston-calibrator
/usr/bin/weston-clickdot
/usr/bin/weston-cliptest
/usr/bin/weston-dnd
/usr/bin/weston-editor
/usr/bin/weston-eventdemo
/usr/bin/weston-flower
/usr/bin/weston-fullscreen
/usr/bin/weston-image
/usr/bin/weston-multi-resource
/usr/bin/weston-presentation-shm
/usr/bin/weston-resizor
/usr/bin/weston-scaler
/usr/bin/weston-simple-damage
/usr/bin/weston-simple-dmabuf-v4l
/usr/bin/weston-simple-egl
/usr/bin/weston-simple-shm
/usr/bin/weston-simple-touch
/usr/bin/weston-smoke
/usr/bin/weston-stacking
/usr/bin/weston-subsurfaces
/usr/bin/weston-transformed

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libweston-14.so.0.0.2
/V3/usr/lib64/libweston-14/color-lcms.so
/V3/usr/lib64/libweston-14/drm-backend.so
/V3/usr/lib64/libweston-14/gl-renderer.so
/V3/usr/lib64/libweston-14/headless-backend.so
/V3/usr/lib64/libweston-14/pipewire-backend.so
/V3/usr/lib64/libweston-14/pipewire-plugin.so
/V3/usr/lib64/libweston-14/rdp-backend.so
/V3/usr/lib64/libweston-14/remoting-plugin.so
/V3/usr/lib64/libweston-14/wayland-backend.so
/V3/usr/lib64/libweston-14/x11-backend.so
/V3/usr/lib64/libweston-14/xwayland.so
/V3/usr/lib64/weston/desktop-shell.so
/V3/usr/lib64/weston/fullscreen-shell.so
/V3/usr/lib64/weston/hmi-controller.so
/V3/usr/lib64/weston/ivi-shell.so
/V3/usr/lib64/weston/kiosk-shell.so
/V3/usr/lib64/weston/libexec_weston.so.0.0.0
/V3/usr/lib64/weston/screen-share.so
/V3/usr/lib64/weston/systemd-notify.so
/usr/lib64/libweston-14.so.0
/usr/lib64/libweston-14.so.0.0.2
/usr/lib64/libweston-14/color-lcms.so
/usr/lib64/libweston-14/drm-backend.so
/usr/lib64/libweston-14/gl-renderer.so
/usr/lib64/libweston-14/headless-backend.so
/usr/lib64/libweston-14/pipewire-backend.so
/usr/lib64/libweston-14/pipewire-plugin.so
/usr/lib64/libweston-14/rdp-backend.so
/usr/lib64/libweston-14/remoting-plugin.so
/usr/lib64/libweston-14/wayland-backend.so
/usr/lib64/libweston-14/x11-backend.so
/usr/lib64/libweston-14/xwayland.so
/usr/lib64/weston/desktop-shell.so
/usr/lib64/weston/fullscreen-shell.so
/usr/lib64/weston/hmi-controller.so
/usr/lib64/weston/ivi-shell.so
/usr/lib64/weston/kiosk-shell.so
/usr/lib64/weston/libexec_weston.so
/usr/lib64/weston/libexec_weston.so.0
/usr/lib64/weston/libexec_weston.so.0.0.0
/usr/lib64/weston/screen-share.so
/usr/lib64/weston/systemd-notify.so

%files libexec
%defattr(-,root,root,-)
/V3/usr/libexec/weston-desktop-shell
/V3/usr/libexec/weston-ivi-shell-user-interface
/V3/usr/libexec/weston-keyboard
/V3/usr/libexec/weston-simple-im
/usr/libexec/weston-desktop-shell
/usr/libexec/weston-ivi-shell-user-interface
/usr/libexec/weston-keyboard
/usr/libexec/weston-simple-im

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/weston/3cdd630da43ea78f8ca83b291afcce3fa388a804
/usr/share/package-licenses/weston/5648ca4646a6d77ee875a10a0f8a576f59d8cb44

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/weston-debug.1
/usr/share/man/man1/weston.1
/usr/share/man/man5/weston.ini.5
/usr/share/man/man7/weston-bindings.7
/usr/share/man/man7/weston-drm.7
/usr/share/man/man7/weston-rdp.7
