#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x11A30156E0E67611 (bryce@ubuntu.com)
#
Name     : weston
Version  : 3.0.0
Release  : 10
URL      : https://wayland.freedesktop.org/releases/weston-3.0.0.tar.xz
Source0  : https://wayland.freedesktop.org/releases/weston-3.0.0.tar.xz
Source99 : https://wayland.freedesktop.org/releases/weston-3.0.0.tar.xz.sig
Summary  : Header files for Weston plugin development
Group    : Development/Tools
License  : MIT
Requires: weston-bin
Requires: weston-lib
Requires: weston-doc
Requires: weston-data
BuildRequires : Linux-PAM-dev
BuildRequires : doxygen
BuildRequires : lcms2-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(cairo-xcb)
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(egl)
BuildRequires : pkgconfig(gbm)
BuildRequires : pkgconfig(glesv2)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(libdrm)
BuildRequires : pkgconfig(libinput)
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pkgconfig(libudev)
BuildRequires : pkgconfig(libunwind)
BuildRequires : pkgconfig(libva)
BuildRequires : pkgconfig(libva-drm)
BuildRequires : pkgconfig(libwebp)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(mtdev)
BuildRequires : pkgconfig(pango)
BuildRequires : pkgconfig(pangocairo)
BuildRequires : pkgconfig(pixman-1)
BuildRequires : pkgconfig(wayland-client)
BuildRequires : pkgconfig(wayland-cursor)
BuildRequires : pkgconfig(wayland-egl)
BuildRequires : pkgconfig(wayland-protocols)
BuildRequires : pkgconfig(wayland-scanner)
BuildRequires : pkgconfig(wayland-server)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xcb)
BuildRequires : pkgconfig(xcb-composite)
BuildRequires : pkgconfig(xcb-xfixes)
BuildRequires : pkgconfig(xcb-xkb)
BuildRequires : pkgconfig(xcursor)
BuildRequires : pkgconfig(xkbcommon)
BuildRequires : sed

%description
Weston
======
Weston is the reference implementation of a Wayland compositor, and a
useful compositor in its own right.  Weston has various backends that
lets it run on Linux kernel modesetting and evdev input as well as
under X11.  Weston ships with a few example clients, from simple
clients that demonstrate certain aspects of the protocol to more
complete clients and a simplistic toolkit.  There is also a quite
capable terminal emulator (weston-terminal) and an toy/example desktop
shell.  Finally, weston also provides integration with the Xorg server
and can pull X clients into the Wayland desktop and act as an X window
manager.

%package bin
Summary: bin components for the weston package.
Group: Binaries
Requires: weston-data

%description bin
bin components for the weston package.


%package data
Summary: data components for the weston package.
Group: Data

%description data
data components for the weston package.


%package dev
Summary: dev components for the weston package.
Group: Development
Requires: weston-lib
Requires: weston-bin
Requires: weston-data
Provides: weston-devel

%description dev
dev components for the weston package.


%package doc
Summary: doc components for the weston package.
Group: Documentation

%description doc
doc components for the weston package.


%package lib
Summary: lib components for the weston package.
Group: Libraries
Requires: weston-data

%description lib
lib components for the weston package.


%prep
%setup -q -n weston-3.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1502223444
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -fno-semantic-interposition "
%configure --disable-static --disable-documentation \
--disable-setuid-install
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1502223444
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/wcap-decode
/usr/bin/weston
/usr/bin/weston-info
/usr/bin/weston-launch
/usr/bin/weston-terminal
/usr/libexec/weston-desktop-shell
/usr/libexec/weston-ivi-shell-user-interface
/usr/libexec/weston-keyboard
/usr/libexec/weston-screenshooter
/usr/libexec/weston-simple-im

%files data
%defattr(-,root,root,-)
/usr/share/wayland-sessions/weston.desktop
/usr/share/weston/background.png
/usr/share/weston/border.png
/usr/share/weston/fullscreen.png
/usr/share/weston/home.png
/usr/share/weston/icon_editor.png
/usr/share/weston/icon_flower.png
/usr/share/weston/icon_ivi_clickdot.png
/usr/share/weston/icon_ivi_flower.png
/usr/share/weston/icon_ivi_simple-egl.png
/usr/share/weston/icon_ivi_simple-shm.png
/usr/share/weston/icon_ivi_smoke.png
/usr/share/weston/icon_terminal.png
/usr/share/weston/icon_window.png
/usr/share/weston/panel.png
/usr/share/weston/pattern.png
/usr/share/weston/random.png
/usr/share/weston/sidebyside.png
/usr/share/weston/sign_close.png
/usr/share/weston/sign_maximize.png
/usr/share/weston/sign_minimize.png
/usr/share/weston/terminal.png
/usr/share/weston/tiling.png
/usr/share/weston/wayland.png
/usr/share/weston/wayland.svg

%files dev
%defattr(-,root,root,-)
/usr/include/libweston-3/compositor-drm.h
/usr/include/libweston-3/compositor-fbdev.h
/usr/include/libweston-3/compositor-headless.h
/usr/include/libweston-3/compositor-rdp.h
/usr/include/libweston-3/compositor-wayland.h
/usr/include/libweston-3/compositor-x11.h
/usr/include/libweston-3/compositor.h
/usr/include/libweston-3/config-parser.h
/usr/include/libweston-3/libweston-desktop.h
/usr/include/libweston-3/matrix.h
/usr/include/libweston-3/plugin-registry.h
/usr/include/libweston-3/timeline-object.h
/usr/include/libweston-3/version.h
/usr/include/libweston-3/windowed-output-api.h
/usr/include/libweston-3/xwayland-api.h
/usr/include/libweston-3/zalloc.h
/usr/include/weston/ivi-layout-export.h
/usr/include/weston/weston.h
/usr/lib64/libweston-3.so
/usr/lib64/libweston-desktop-3.so
/usr/lib64/pkgconfig/libweston-3.pc
/usr/lib64/pkgconfig/libweston-desktop-3.pc
/usr/lib64/pkgconfig/weston.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
%doc /usr/share/man/man5/*
%doc /usr/share/man/man7/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libweston-3.so.0
/usr/lib64/libweston-3.so.0.0.0
/usr/lib64/libweston-3/drm-backend.so
/usr/lib64/libweston-3/fbdev-backend.so
/usr/lib64/libweston-3/gl-renderer.so
/usr/lib64/libweston-3/headless-backend.so
/usr/lib64/libweston-3/wayland-backend.so
/usr/lib64/libweston-3/x11-backend.so
/usr/lib64/libweston-3/xwayland.so
/usr/lib64/libweston-desktop-3.so.0
/usr/lib64/libweston-desktop-3.so.0.0.0
/usr/lib64/weston/cms-static.so
/usr/lib64/weston/desktop-shell.so
/usr/lib64/weston/fullscreen-shell.so
/usr/lib64/weston/hmi-controller.so
/usr/lib64/weston/ivi-shell.so
